[jenkins]
172.16.3.138 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/upgrad_key.pem

[apps]
172.16.2.16 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/upgrad-key.pem
